### ISSUE TITLE
Module works with AWS provider 3, random provider 3, Terraform 0.14

### ISSUE THREAD

**Issue by sjmiller609** [marbot-io/terraform-aws-marbot-monitoring-basic#2]
Hey Marbot team. I'm giving this module a shot. We are using some newer versions for providers and terraform.

```
stevencerebral@Stevens-MacBook-Pro dev % terraform --version
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.28.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
```

I did a Terraform init to download your module, then manually patched the module in my .terraform directory to see what would happen. It applied without an issue.
```
   2   required_version = "~> 0.14"
   3   required_providers {
   4     aws    = ">= 2.48.0"
   5     random = ">= 2.2"
   6   }
   7 }
   8
```
above: just checking if it would work, not best practice.

Just letting you know - you might consider publishing a new module version with the versioning constraints updated. Thanks for your open source contributions!

**Comment by michaelwittig** [comment]
Hi! Thanks for reporting this. I agree that our tf version requirement is too strict. Could you test version `0.12.1` of the module?
